---

name: Check Commit Message

on: [push, pull_request]
jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install exlg-git-commit-msg-std
        run: |
          npm config set registry http://registry.npmjs.org/
          yarn config set registry https://registry.yarnpkg.com
          yarn add exlg-git-commit-msg-std